ftp_pwd:
  - ftp
  - www
  - '{{blank}}'
  - '{{common_pwd}}'
mongo_pwd:
  - mongo
  - '{{common_pwd}}'
mysql_pwd:
  - mysql
  - root
  - '{{blank}}'
  - '{{common_pwd}}'
mssql_pwd:
  - sa
  - '{{common_pwd}}'
postgresql_pwd:
  - '{{blank}}'
  - postgre
  - postgresql
  - '{{common_pwd}}'
rdp_pwd:
  - '{{common_pwd}}'
redis_pwd:
  - '{{blank}}'
  - redis
  - '{{common_pwd}}'
smb_pwd:
  - '{{common_pwd}}'
ssh_pwd:
  - admin@huawei.com
  - '{{common_pwd}}'
ftp_user:
  - ftp
  - admin
  - www
  - anonymous
mysql_user:
  - root
  - mysql
  - admin
mssql_user:
  - sa
smb_user:
  - administrator
  - admin
rdp_user:
  - administrator
  - admin
postgresql_user:
  - postgres
  - admin
ssh_user:
  - root
  - admin
mongo_user:
  - root
  - admin
redis_user:
  - root